### ISSUE TITLE
Add a README.md

### ISSUE THREAD

**Issue by NatoBoram** [StonehearthACE-team/stonehearth_ace#13]
The project is kind of hard to land on. It would greatly benefit having a `README.md` to at least inform newcomers of how to install it and for useful links like the [discourse](https://discourse.stonehearth.net/t/ace-authorized-community-expansion-project/36671) topic.

**Comment by paulthegreat** [comment]
Anyone who has landed on it should probably have landed on it through the Discourse or Discord server. Once it's in a more stable state, it will be readily available in-game in Stonehearth (and visible on the Steam Workshop), with no need for installation instructions, and there will be more documentation. This will also be very soon.

**Comment by NatoBoram** [comment]
I've landed from the Discourse thread, but I didn't find any installation instructions there either. I had to speak to @Cirdain on Discord to know how to install it and to know that I have to checkout to `unstable-work` if I wanted to test where's the mod at.

We don't have all the same path to this repo. I understand that the `README.md` I'm asking would be of fairly minimal use, but it's okay if it's also of minimal content, just enough to get started.

Here's an example of what I think should be in the temporary `README.md` : 

```markdown
# Stonehearth ACE

Follow the **A**uthorized **C**ommunity **E**xpansion project on [Discourse](https://discourse.stonehearth.net/t/ace-authorized-community-expansion-project/36671)!

## Installation

1. Click on **Clone or download**
2. **Download as ZIP**
3. Put it inside the game's files, in the `mods` folder.
```

**Comment by paulthegreat** [comment]
Sure, I can add that. There is a line directly above the github link on the Discourse, though, that says this:
> The most recent version is always on the ‘unstable-work’ branch!
