### ISSUE TITLE
Manifest.json line 1140 folder error

### ISSUE THREAD

**Issue by WolfBlader** [StonehearthACE-team/stonehearth_ace#16]
Hello,
There is a folder error for the tree_stump in line 1140
think it should be
"stonehearth:mixins:tree": "file(components/stump/add_stump.json)",

instead of
"stonehearth:mixins:tree": "file(components/tree_stump/add_stump.json)",

also got other tree related issues in stonehearth.log
line 1169 to 1176 json files are missing.
"archipelago_biome:trees:bend_palm:large": "file(entities/trees/bend_palm_tree/large_bend_palm_tree)",
      "archipelago_biome:trees:bend_palm:small": "file(entities/trees/bend_palm_tree/small_bend_palm_tree)",
      "archipelago_biome:trees:dranden:small": "file(entities/trees/dranden)",
      "archipelago_biome:trees:palm:large": "file(entities/trees/palm_tree/large_palm_tree)",
      "archipelago_biome:trees:palm:small": "file(entities/trees/palm_tree/small_palm_tree)",
      "archipelago_biome:trees:palm:sapling": "file(entities/trees/palm_tree/small_palm_tree)",
      "archipelago_biome:trees:papaya": "file(entities/trees/papaya)",
      "archipelago_biome:trees:smalea:small": "file(entities/trees/smalea)",

Hope it helps.
Wolf

**Comment by paulthegreat** [comment]
Correct about the tree stump, thanks! The other "errors" are just
compatibility for the Archipelago mod in case the user has that, and have
no negative effects. Personally, I think that any mod other than ACE, no
matter how popular, should handle compatibility with ACE, not the other way
around, if only for the simple reason of avoiding circular dependencies. :-P

**Comment by DaniAngione** [comment]
Thank you :) 

I agree with that, although compatibility with Archipelago in this case is more of a courtesy since the files were already made when Bruno provided the tree stump mod :)
