### ISSUE TITLE
Release tags?

### ISSUE THREAD

**Issue by HardCode4All** [StonehearthACE-team/stonehearth_ace#22]
I know this is not a real _issue_, but I couldn't find another way to contact you guys as a team.

Wouldn't it make sense to tag the "release" versions of ACE? I know that the "0.9.2" has been released on steam and [apparently](https://github.com/StonehearthACE-team/stonehearth_ace/commit/fd9281ccda42c3810156c12c1029e08fc282a0ed) there is already a 0.9.3 out there somewhere. But there are no tags / releases in this repo. 

I made the mistake to just download the _current_ ACE a few days ago and since then my game gives me 3-4 UI errors when loading a savegame and crashes quite frequently :(

So I would really wish for stable releases here in the repo that don't crash your game. Thanks in advance.

**Comment by HardCode4All** [comment]
Is anybody reading this?

**Comment by paulthegreat** [comment]
The link at the top takes you to the Discourse discussion thread that's the origin of this whole thing, and provides all the information including methods of communication and a stable version via the latest "News & Updates" item.
