### ISSUE TITLE
Fish population

### ISSUE THREAD

**Issue by Xphine** [StonehearthACE-team/stonehearth_ace#27]
Is there a cap on the fish population? After playing for some time, my small pond has like 500 of them and I fear this will affect performance somehow.
Cheers.

**Comment by DaniAngione** [comment]
Is it an old save? That is, prior to the release of 0.9.3?
Could we have the save file to take a look? Thanks!

**Comment by Xphine** [comment]
This is on unstable branch 0.9.3, I downloaded from here a week or two ago. Also a new save start on 0.9.3.

[Save.zip](https://github.com/StonehearthACE-team/stonehearth_ace/files/3046464/Save.zip)

**Comment by Xphine** [comment]
Thanks, most of the fish despawned. I consider this fixed.
