### ISSUE TITLE
Data error when extracting files

### ISSUE THREAD

**Issue by shadowhollow4** [StonehearthACE-team/stonehearth_ace#54]
the data error is located at data\texture_gradient\skybox\sunny_hot\sky_gradient.png 
It will refuse to extract regardless of how may times I redownload and how many different programs I use to attempt to extract it.

**Comment by paulthegreat** [comment]
Looks just fine to me: https://github.com/StonehearthACE-team/stonehearth_ace/blob/unstable-work/data/texture_gradient/skybox/sunny_hot/sky_gradient.png
